on: ["push","pull_request"]

name: Test Coveralls

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodeVer:
          - "15.9.0"
          - "17.2.0"
          - "lts/*"
          - "node"
    steps:

      - uses: actions/checkout@master

      - name: Use Node.js 18.x
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.nodeVer }}

      - name: Run tests
        run: |
          npm ci
          npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
